/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentación;

import Entidad.ClsEDocumento;
import Entidad.ClsEKardex;
import Entidad.ClsEProducto;
import Entidad.ClsEProveedor;
import Negocio.ClsNDocumento;
import Negocio.ClsNKardex;
import Negocio.ClsNProducto;
import Negocio.ClsNProveedor;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Usuario
 */
public class FrmKardex extends javax.swing.JInternalFrame {
public static String[][] Producto=new String[50][50];
    public static int x=0,y=0,contCod=0,contKar=0;
    public static String[] AyudaProducto=new String[13];
    public static int fila=0,filak=0,stock1=0,fila2=0,multi2=0, bandera=0,l=0;
    public static String c4="0",c5="0",c6="0";
    public static int[] ayudastock=new int[13];
    
    
    
    
    DefaultTableModel modelo,modelo2;
    /**
     * Creates new form FrmKardex
     */
    public FrmKardex() {
        initComponents();
        try {
            this.setMaximum(true);
        
        } catch (Exception e) {
        }
        rbtnCodigoBarra.setSelected(true);
        modelo=new DefaultTableModel();
        modelo.addColumn("CÓDIGO");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("UNIDAD");
        modelo.addColumn("FECHA");
        this.tbProducto.setModel(modelo);
        
        modelo2=new DefaultTableModel();
        modelo2.addColumn("NRO TRANSACCIÓN");//AUTOMATICO
        modelo2.addColumn("CÓDIGO");
        modelo2.addColumn("PRODUCTO");
        modelo2.addColumn("UNIDAD");
        //DOCUMENTO
        modelo2.addColumn("TIPO");
        modelo2.addColumn("NRO. DOC");
        modelo2.addColumn("PROVEEDOR");
        modelo2.addColumn("FECHA");
        //MOVIMIENTO
        modelo2.addColumn("OPERACIÓN");
        modelo2.addColumn("CANTIDAD");
        modelo2.addColumn("CANT. UNIDAD");
        modelo2.addColumn("STOCK");
        this.tbKardex.setModel(modelo2);
        
        MtdlistarProductos();
        LlenarProveedor();
        LlenarDocumento();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbProducto = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbKardex = new javax.swing.JTable();
        grupo2kar2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        cmbProveedor = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        txtNumDoc2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        cmbDocumento = new javax.swing.JComboBox();
        grupo1kar = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtNomProkar = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtKarNroTran = new javax.swing.JTextField();
        txtCodProdkar = new javax.swing.JTextField();
        txtUnidad = new javax.swing.JTextField();
        grupo4kar = new javax.swing.JPanel();
        btnCancelarkar = new javax.swing.JButton();
        btnModificarkar = new javax.swing.JButton();
        btnaceptarkardex = new javax.swing.JButton();
        grupo3kar = new javax.swing.JLayeredPane();
        cmbMov = new javax.swing.JComboBox();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtCantlUni = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtstockmin = new javax.swing.JTextField();
        txtstockmax = new javax.swing.JTextField();
        jdtFecha2 = new com.toedter.calendar.JDateChooser();
        jSeparator1 = new javax.swing.JSeparator();
        txtBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        rbtnCodigoBarra = new javax.swing.JRadioButton();
        rbtnNombre = new javax.swing.JRadioButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setEnabled(false);
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 64, 452, -1));

        tbProducto.setBackground(new java.awt.Color(153, 255, 204));
        tbProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbProductoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbProducto);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 125, -1, 210));

        tbKardex.setBackground(new java.awt.Color(255, 255, 204));
        tbKardex.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbKardex.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbKardexMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbKardex);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 396, 1160, 158));

        grupo2kar2.setBorder(javax.swing.BorderFactory.createTitledBorder("Documento"));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Tipo:");

        cmbProveedor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbProveedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Proveedor1", "Proveedor2", "Proveedor3" }));
        cmbProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProveedorActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Número:");

        txtNumDoc2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Proveedor:");

        cmbDocumento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbDocumento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Factura", "Boleta" }));
        cmbDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDocumentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout grupo2kar2Layout = new javax.swing.GroupLayout(grupo2kar2);
        grupo2kar2.setLayout(grupo2kar2Layout);
        grupo2kar2Layout.setHorizontalGroup(
            grupo2kar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupo2kar2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNumDoc2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbProveedor, 0, 181, Short.MAX_VALUE)
                .addContainerGap())
        );
        grupo2kar2Layout.setVerticalGroup(
            grupo2kar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupo2kar2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(grupo2kar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel23)
                    .addComponent(txtNumDoc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(grupo2kar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 657, -1));

        grupo1kar.setBackground(new java.awt.Color(204, 255, 204));
        grupo1kar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Codigo de Producto:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Numero Transaccion:");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("Nombre:");

        txtNomProkar.setColumns(20);
        txtNomProkar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNomProkar.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNomProkar.setEnabled(false);
        txtNomProkar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomProkarActionPerformed(evt);
            }
        });
        txtNomProkar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomProkarKeyTyped(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Unidad:");

        txtKarNroTran.setEditable(false);

        txtCodProdkar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtCodProdkarMouseEntered(evt);
            }
        });
        txtCodProdkar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodProdkarActionPerformed(evt);
            }
        });
        txtCodProdkar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodProdkarKeyTyped(evt);
            }
        });

        txtUnidad.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtUnidad.setEnabled(false);

        grupo1kar.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        grupo1kar.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        grupo1kar.setLayer(jLabel24, javax.swing.JLayeredPane.DEFAULT_LAYER);
        grupo1kar.setLayer(txtNomProkar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        grupo1kar.setLayer(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        grupo1kar.setLayer(txtKarNroTran, javax.swing.JLayeredPane.DEFAULT_LAYER);
        grupo1kar.setLayer(txtCodProdkar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        grupo1kar.setLayer(txtUnidad, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout grupo1karLayout = new javax.swing.GroupLayout(grupo1kar);
        grupo1kar.setLayout(grupo1karLayout);
        grupo1karLayout.setHorizontalGroup(
            grupo1karLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupo1karLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(grupo1karLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(grupo1karLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(txtCodProdkar))
                    .addGroup(grupo1karLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomProkar, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(grupo1karLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, grupo1karLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18))
                    .addGroup(grupo1karLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(112, 112, 112)))
                .addGroup(grupo1karLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtKarNroTran, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
        grupo1karLayout.setVerticalGroup(
            grupo1karLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, grupo1karLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(grupo1karLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(txtKarNroTran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodProdkar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(grupo1karLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtNomProkar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(txtUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(grupo1kar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 657, -1));

        grupo4kar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnCancelarkar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancelarkar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancelar2.png"))); // NOI18N
        btnCancelarkar.setText("CANCELAR");
        btnCancelarkar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarkarActionPerformed(evt);
            }
        });

        btnModificarkar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnModificarkar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/modificar.png"))); // NOI18N
        btnModificarkar.setText("MODIFICAR");
        btnModificarkar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarkarActionPerformed(evt);
            }
        });

        btnaceptarkardex.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnaceptarkardex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/insertar.png"))); // NOI18N
        btnaceptarkardex.setText("INSERTAR");
        btnaceptarkardex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaceptarkardexActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout grupo4karLayout = new javax.swing.GroupLayout(grupo4kar);
        grupo4kar.setLayout(grupo4karLayout);
        grupo4karLayout.setHorizontalGroup(
            grupo4karLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupo4karLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(btnaceptarkardex, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(btnModificarkar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(btnCancelarkar)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        grupo4karLayout.setVerticalGroup(
            grupo4karLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, grupo4karLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(grupo4karLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnaceptarkardex, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarkar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarkar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(grupo4kar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 657, -1));

        grupo3kar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MOVIMIENTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        cmbMov.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbMov.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Entrada", "Salida" }));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("Cantidad unidad:");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setText("Stock:");

        txtCantlUni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantlUniKeyReleased(evt);
            }
        });

        txtStock.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtStockKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Operacion:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Fecha:");

        txtstockmin.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtstockmin.setEnabled(false);

        txtstockmax.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtstockmax.setEnabled(false);

        grupo3kar.setLayer(cmbMov, javax.swing.JLayeredPane.DEFAULT_LAYER);
        grupo3kar.setLayer(jLabel25, javax.swing.JLayeredPane.DEFAULT_LAYER);
        grupo3kar.setLayer(jLabel26, javax.swing.JLayeredPane.DEFAULT_LAYER);
        grupo3kar.setLayer(txtCantlUni, javax.swing.JLayeredPane.DEFAULT_LAYER);
        grupo3kar.setLayer(txtStock, javax.swing.JLayeredPane.DEFAULT_LAYER);
        grupo3kar.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        grupo3kar.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        grupo3kar.setLayer(txtstockmin, javax.swing.JLayeredPane.DEFAULT_LAYER);
        grupo3kar.setLayer(txtstockmax, javax.swing.JLayeredPane.DEFAULT_LAYER);
        grupo3kar.setLayer(jdtFecha2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout grupo3karLayout = new javax.swing.GroupLayout(grupo3kar);
        grupo3kar.setLayout(grupo3karLayout);
        grupo3karLayout.setHorizontalGroup(
            grupo3karLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupo3karLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(grupo3karLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(grupo3karLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(62, 62, 62)
                        .addComponent(cmbMov, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(txtstockmin, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtstockmax, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, grupo3karLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(18, 18, 18)
                        .addComponent(txtCantlUni, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel26)))
                .addGroup(grupo3karLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(grupo3karLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jdtFecha2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(grupo3karLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        grupo3karLayout.setVerticalGroup(
            grupo3karLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupo3karLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(grupo3karLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(grupo3karLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(cmbMov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(txtstockmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtstockmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jdtFecha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(grupo3karLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtCantlUni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(grupo3kar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 40, 650, -1));

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });
        getContentPane().add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 111, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search.png"))); // NOI18N
        jLabel1.setText("BUSCADOR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        buttonGroup2.add(rbtnCodigoBarra);
        rbtnCodigoBarra.setText("Codigo de barras");
        getContentPane().add(rbtnCodigoBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, -1));

        buttonGroup2.add(rbtnNombre);
        rbtnNombre.setText("Nombre");
        getContentPane().add(rbtnNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProductoMouseClicked
//        fila2=tbRegistro.getSelectedRow();
//        //fila=tbldatos.
//
//        txtCodProd1.setText(tbRegistro.getValueAt(fila2, 0).toString());
//        txtNomPro1.setText(tbRegistro.getValueAt(fila2, 1).toString());
//        cbTipoUni1.setSelectedItem(tbRegistro.getValueAt(fila2, 2).toString());
//
//        DateFormat formato=new SimpleDateFormat("dd-MM-yyyy");
//        String f=(String)tbRegistro.getValueAt(fila2, 3);
//        Date fechaa=null;
//        try {
//            fechaa=formato.parse(f);
//            jdtFecha1.setDate(fechaa);
//        } catch (ParseException ex) {
//            ex.printStackTrace();
//        }

    }//GEN-LAST:event_tbProductoMouseClicked

    private void tbKardexMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbKardexMouseClicked
        int filam;                                   //PASAR DATOS DE LA TABLA A LAS CAJAS DE TEXTO
        filam=tbKardex.getSelectedRow();   
        txtKarNroTran.setText(tbKardex.getValueAt(filam, 0).toString());
        if(tbKardex.getValueAt(filam, 1).toString().equals("Entrada"))
        {
            cmbMov.setSelectedIndex(0);
        }
        else
        {
            cmbMov.setSelectedIndex(1);
        }
        txtCantlUni.setText(tbKardex.getValueAt(filam, 2).toString());
         DateFormat formato=new SimpleDateFormat("yyyy-MM-dd");
        String f=(String)tbKardex.getValueAt(filam, 3);
        java.util.Date fechaa=null;       
        try {
            fechaa=formato.parse(f);
            jdtFecha2.setDate(fechaa);
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
        cmbDocumento.setSelectedIndex(Integer.parseInt(tbKardex.getValueAt(filam, 5).toString())-1);
        cmbProveedor.setSelectedIndex(Integer.parseInt(tbKardex.getValueAt(filam, 6).toString())-1);
        txtCodProdkar.setText(tbKardex.getValueAt(filam, 7).toString());
        txtCantlUni.setEnabled(false);
        txtUnidad.setEnabled(false);
        txtStock.setEnabled(false);
        txtstockmax.setEnabled(false);
        txtstockmin.setEnabled(false);
        cmbMov.setEnabled(false);

    }//GEN-LAST:event_tbKardexMouseClicked

    private void cmbProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProveedorActionPerformed
        //interfaz.verDocumento(cbNomProv, txtDocCod);
    }//GEN-LAST:event_cmbProveedorActionPerformed

    private void cmbDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDocumentoActionPerformed

    private void txtNomProkarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomProkarActionPerformed
//        for(int i=0;i<x;i++)
//        {
//            if(txtNomProkar.getText().equals(Producto[i][1]))
//            {
//                filak=i;
//                cbTipoUnikar.setSelectedItem(Producto[i][2]);
//                txtCodProdkar.setText(Producto[i][0]);
//            }
//        }
    }//GEN-LAST:event_txtNomProkarActionPerformed

    private void txtNomProkarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomProkarKeyTyped

    }//GEN-LAST:event_txtNomProkarKeyTyped

    private void txtCodProdkarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodProdkarMouseEntered

    }//GEN-LAST:event_txtCodProdkarMouseEntered

    private void txtCodProdkarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodProdkarActionPerformed
        ClsEProducto objEE=new ClsEProducto();
        ClsNProducto objNE=new ClsNProducto();
        objEE.setCBarras(txtCodProdkar.getText());
        Principal.ayuda=0;  
        if(objNE.MtdBuscarProducto(objEE)==true)
        {
            if(txtstockmax.getText().equals("0") && txtstockmin.getText().equals("0"))
            {
                txtstockmax.setEnabled(true);
                txtstockmin.setEnabled(true);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "PRODUCTO NO EXISTE O SE ENCUENTRA INACTIVO");
        }


    }//GEN-LAST:event_txtCodProdkarActionPerformed

    private void txtCodProdkarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodProdkarKeyTyped

           

    }//GEN-LAST:event_txtCodProdkarKeyTyped

    private void btnCancelarkarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarkarActionPerformed
        txtBuscar.setText("");
         txtCantlUni.setText("");
         txtCodProdkar.setText("");
         jdtFecha2.setDate(null);
         txtKarNroTran.setText("");
         txtNomProkar.setText("");
         txtNumDoc2.setText("");
         txtStock.setText("");
         txtUnidad.setText("");
         txtstockmax.setText("");
         txtstockmin.setText("");
         cmbDocumento.setSelectedIndex(0);
         cmbMov.setSelectedIndex(0);
         cmbProveedor.setSelectedIndex(0);
         cmbMov.setEnabled(true);
         txtCantlUni.setEnabled(true);
    }//GEN-LAST:event_btnCancelarkarActionPerformed

    private void btnModificarkarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarkarActionPerformed

        Date fecha=jdtFecha2.getDate();
        DateFormat formato=new SimpleDateFormat("yyyy-MM-dd");
        String f=formato.format(fecha);
        ClsEKardex objEE=new ClsEKardex();
        ClsNKardex objNE=new ClsNKardex();
        objEE.setNtransaccion(Integer.parseInt(txtKarNroTran.getText()));
        objEE.setFecha(f);
        objEE.setIdDocumento(cmbDocumento.getSelectedIndex()+1);
        objEE.setIdProveedor(cmbProveedor.getSelectedIndex()+1);
        if(objNE.MtdModificarKardex(objEE)==true)
        {
            JOptionPane.showMessageDialog(null, "DATOS MODIFICADOS CORRECTAMENTE");
            MtdListar();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "NO SE PUDO MODIFICAR EL DATO");
        }
        
    }//GEN-LAST:event_btnModificarkarActionPerformed

    private void btnaceptarkardexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaceptarkardexActionPerformed
        Date fecha=jdtFecha2.getDate();
        DateFormat formato=new SimpleDateFormat("yyyy-MM-dd");
        String f=formato.format(fecha);
        ClsEKardex objEE=new ClsEKardex();
        ClsNKardex objNE=new ClsNKardex();
        ClsEProducto objEEE=new ClsEProducto();
        ClsNProducto objNEE=new ClsNProducto();
        //actualizar stock minimo y maximo de producto
        objEEE.setsMinimo(Integer.parseInt(txtstockmin.getText()));
        objEEE.setsMaximo(Integer.parseInt(txtstockmax.getText()));
        objEEE.setCBarras(txtCodProdkar.getText());
        //Ingresar al kardex
        objEE.setOperacion(String.valueOf(cmbMov.getSelectedItem()));
        objEE.setCantidad(Integer.parseInt(txtCantlUni.getText()));
        objEE.setFecha(f);
        objEE.setIdEmpleado(Principal.IDempleado);
        objEE.setIdDocumento(cmbDocumento.getSelectedIndex()+1);
        objEE.setIdProveedor(cmbProveedor.getSelectedIndex()+1);
        objEE.setcBarras(txtCodProdkar.getText());
       
        int cantidad,stock,minimo,maximo,ope;
            cantidad=Integer.parseInt(txtCantlUni.getText());
            stock=Integer.parseInt(txtStock.getText());
            minimo=Integer.parseInt(txtstockmin.getText());
            maximo=Integer.parseInt(txtstockmax.getText());
            
        if(cmbMov.getSelectedIndex()==0)
        {
            ope=cantidad+stock;
            objEEE.setStock(ope);
            objEE.setStock(ope);
            if(ope>=minimo && ope<=maximo)
            {
                if(objNEE.MtdModificarProducto2(objEEE)==true)
                {
                    if(objNE.MtdResgistrarKardex(objEE)==true)
                    {
                        JOptionPane.showMessageDialog(null, "Registro correcto");
                        MtdListar();
                        MtdlistarProductos();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "NO SE PUDO GUARDAR DATOS");
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "NO SE PUDO MODIFICAR EL DATO");
                }
                
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Su operación está fuera del rango de minimo y maximo");
            }        
        }
        else
        {
            ope=stock-cantidad;
            objEEE.setStock(ope);
            objEE.setStock(ope);
            if(ope>=minimo && ope<=maximo)
            {
                if(objNEE.MtdModificarProducto2(objEEE)==true)
                {
                    if(objNE.MtdResgistrarKardex(objEE)==true)
                    {
                        JOptionPane.showMessageDialog(null, "Registro correcto");
                        MtdListar();
                        MtdlistarProductos();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "NO SE PUDO GUARDAR DATOS");
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "NO SE PUDO MODIFICAR EL DATO");
                }
                
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Su operación está fuera del rango de minimo y maximo");
            }
        }

    }//GEN-LAST:event_btnaceptarkardexActionPerformed

    private void txtCantlUniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantlUniKeyReleased
        //interfaz.calcular(txtCant, txtValUni, txtValTot, 2);
    }//GEN-LAST:event_txtCantlUniKeyReleased

    private void txtStockKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockKeyReleased
        //interfaz.calcular(txtCant, txtValUni, txtValTot, 3);
    }//GEN-LAST:event_txtStockKeyReleased
    TableRowSorter trs;
    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped

        txtBuscar.addKeyListener(new KeyAdapter()
        {
            public void keyReleased(KeyEvent e){
                
                if (rbtnCodigoBarra.isSelected()){
                    trs.setRowFilter(RowFilter.regexFilter("(?i)"+txtBuscar.getText(),0));
                }
                if (rbtnNombre.isSelected()){
                    trs.setRowFilter(RowFilter.regexFilter("(?i)"+txtBuscar.getText(),1));
                }
            }
        }
        );
        trs=new TableRowSorter(modelo);
        tbProducto.setRowSorter(trs);
    }//GEN-LAST:event_txtBuscarKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarkar;
    private javax.swing.JButton btnModificarkar;
    private javax.swing.JButton btnaceptarkardex;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox cmbDocumento;
    private javax.swing.JComboBox cmbMov;
    private javax.swing.JComboBox cmbProveedor;
    private javax.swing.JLayeredPane grupo1kar;
    private javax.swing.JPanel grupo2kar2;
    private javax.swing.JLayeredPane grupo3kar;
    private javax.swing.JPanel grupo4kar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private com.toedter.calendar.JDateChooser jdtFecha2;
    private javax.swing.JRadioButton rbtnCodigoBarra;
    private javax.swing.JRadioButton rbtnNombre;
    private javax.swing.JTable tbKardex;
    private javax.swing.JTable tbProducto;
    private javax.swing.JTextField txtBuscar;
    public static javax.swing.JTextField txtCantlUni;
    private javax.swing.JTextField txtCodProdkar;
    private javax.swing.JTextField txtKarNroTran;
    public static javax.swing.JTextField txtNomProkar;
    private javax.swing.JTextField txtNumDoc2;
    public static javax.swing.JTextField txtStock;
    public static javax.swing.JTextField txtUnidad;
    public static javax.swing.JTextField txtstockmax;
    public static javax.swing.JTextField txtstockmin;
    // End of variables declaration//GEN-END:variables

    public void MtdlistarProductos() {
        modelo=new DefaultTableModel();
        modelo.addColumn("CODIGO BARRAS");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("UNIDADES CAJAS");
        modelo.addColumn("UNIDAD");
        modelo.addColumn("STOCK MINIMO");
        modelo.addColumn("STOCK MAXIMO");
        modelo.addColumn("STOCK");
        modelo.addColumn("ESTADO");
        ClsNProducto objNE=new ClsNProducto();
        String[] datos=new String[8];
        for(ClsEProducto objE : objNE.MtdListarProducto())
        {
            if(objE.getEstado()==1)
            {
                datos[0]=objE.getCBarras();
                datos[1]=objE.getNombre();
                datos[2]=String.valueOf(objE.getuCajas());
                datos[3]=String.valueOf(objE.getIdUnidad());
                datos[4]=String.valueOf(objE.getsMinimo());
                datos[5]=String.valueOf(objE.getsMaximo());
                datos[6]=String.valueOf(objE.getStock());
                datos[7]="ACTIVO";
                modelo.addRow(datos);
            }
            
        }
        this.tbProducto.setModel(modelo);
    }

    public void LlenarProveedor() {
         String []prueba=new String[1];
        DefaultComboBoxModel value = new DefaultComboBoxModel();
        cmbProveedor.removeAllItems();
        cmbProveedor.setModel(value);    
        ClsNProveedor objN =new ClsNProveedor();
        for(ClsEProveedor objE : objN.LlenarProveedor())
        {
            if(objE.getEstado()==1)
            {
                prueba[0]=objE.getNombre();
                value.addElement(prueba[0]);
            }                    
        }  
    }

    public void LlenarDocumento() {
        String []prueba=new String[1];
        DefaultComboBoxModel value = new DefaultComboBoxModel();
        cmbDocumento.removeAllItems();
        cmbDocumento.setModel(value);    
        ClsNDocumento objN =new ClsNDocumento();
        for(ClsEDocumento objE : objN.LlenarDocumento())
        {
                prueba[0]=objE.getDescripcion();
                value.addElement(prueba[0]);                              
        }  
    }

    public void MtdListar() {  //kardex
        modelo=new DefaultTableModel();
        modelo.addColumn("Nro Transacción");
        modelo.addColumn("Operación");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Fecha");
        modelo.addColumn("Id Empleado");
        modelo.addColumn("Id Documento");
        modelo.addColumn("Id Proveedor");
        modelo.addColumn("C. Barras");
        modelo.addColumn("Stock");
        ClsNKardex objNE=new ClsNKardex();
        String[] datos=new String[9];
        for(ClsEKardex objE : objNE.MtdListarKardex())
        {
                datos[0]=String.valueOf(objE.getNtransaccion());
                datos[1]=objE.getOperacion();
                datos[2]=String.valueOf(objE.getCantidad());
                datos[3]=objE.getFecha();
                datos[4]=String.valueOf(objE.getIdEmpleado());
                datos[5]=String.valueOf(objE.getIdDocumento());
                datos[6]=String.valueOf(objE.getIdProveedor());
                datos[7]=objE.getcBarras();
                datos[8]=String.valueOf(objE.getStock());
                modelo.addRow(datos);
        }
        this.tbKardex.setModel(modelo);
    }
}
