/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentación;

import Entidad.ClsEEmpleado;
import Negocio.ClsNEmpleado;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class FrmModificar extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmModificar
     */
    public FrmModificar() {
        initComponents();
        initComponents();
        try {
            this.setMaximum(true);
        
        } catch (Exception e) {
        }
//        MtdListarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblApellidos = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        lblFechaNac = new javax.swing.JLabel();
        jdcFechaNac = new com.toedter.calendar.JDateChooser();
        lblSexo = new javax.swing.JLabel();
        rbtnMasculino = new javax.swing.JRadioButton();
        lblDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblContraseña = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JPasswordField();
        rbtnFemenino = new javax.swing.JRadioButton();
        btnGuardarCambios = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 255, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombre.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblNombre.setText("Nombre");
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 70, 30));

        txtNombre.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtNombre.setText("Luis Fernando");
        txtNombre.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 190, 30));

        lblApellidos.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblApellidos.setText("Apellidos");
        getContentPane().add(lblApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, 30));

        txtApellidos.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtApellidos.setText("Flores Querie");
        txtApellidos.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        getContentPane().add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 190, 30));

        lblFechaNac.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblFechaNac.setText("Fecha de nacimiento");
        getContentPane().add(lblFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 160, 30));
        getContentPane().add(jdcFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 190, 30));

        lblSexo.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblSexo.setText("Sexo");
        getContentPane().add(lblSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 40, 30));

        rbtnMasculino.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbtnMasculino);
        rbtnMasculino.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        rbtnMasculino.setText("Masculino");
        getContentPane().add(rbtnMasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, -1, 30));

        lblDireccion.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblDireccion.setText("Direccion");
        getContentPane().add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 80, 30));

        txtDireccion.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtDireccion.setText("Mi casa");
        txtDireccion.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 190, 30));

        lblTelefono.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblTelefono.setText("Telefono");
        getContentPane().add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, 30));

        txtTelefono.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtTelefono.setText("992200011");
        txtTelefono.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 190, 30));

        lblContraseña.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblContraseña.setText("Contraseña");
        getContentPane().add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, 30));

        txtContraseña.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtContraseña.setText("asd");
        txtContraseña.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        getContentPane().add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 140, 30));

        rbtnFemenino.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbtnFemenino);
        rbtnFemenino.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        rbtnFemenino.setText("Femenino");
        getContentPane().add(rbtnFemenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, 100, 30));

        btnGuardarCambios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/modificar.png"))); // NOI18N
        btnGuardarCambios.setText("      GUARDAR CAMBIOS");
        btnGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCambiosActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardarCambios, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 177, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCambiosActionPerformed
         java.util.Date fecha=jdcFechaNac.getDate();
        DateFormat formato=new SimpleDateFormat("yyyy-MM-dd");
        String f=formato.format(fecha);
        ClsEEmpleado objEE=new ClsEEmpleado();
        ClsNEmpleado objNE=new ClsNEmpleado();
        objEE.setDniEmpleado(Principal.txtDni.getText());
        objEE.setNombreEmpleado(txtNombre.getText());
        objEE.setApellidosEmpleado(txtApellidos.getText());
        if(rbtnMasculino.isSelected())
        {
            objEE.setSexoEmpleado("Masculino");
        }
        else
        {
            objEE.setSexoEmpleado("Femenino");
        }
        objEE.setFnacimientoEmpleado(f);
        objEE.setDireccionEmpleado(txtDireccion.getText());
        objEE.setTelefonoEmpleado(txtTelefono.getText());
        objEE.setContraseñaEmpleado(txtContraseña.getText());
   
        if(objNE.MtdModificarEmpleado2(objEE)==true)
        {
            JOptionPane.showMessageDialog(null, "DATOS MODIFICADOS CORRECTAMENTE");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "NO SE PUDO MODIFICAR EL DATO");
        }
    }//GEN-LAST:event_btnGuardarCambiosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarCambios;
    private javax.swing.ButtonGroup buttonGroup1;
    public static com.toedter.calendar.JDateChooser jdcFechaNac;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblFechaNac;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTelefono;
    public static javax.swing.JRadioButton rbtnFemenino;
    public static javax.swing.JRadioButton rbtnMasculino;
    public static javax.swing.JTextField txtApellidos;
    public static javax.swing.JPasswordField txtContraseña;
    public static javax.swing.JTextField txtDireccion;
    public static javax.swing.JTextField txtNombre;
    public static javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

    public void MtdListarDatos() {
        String dni;
        dni = Principal.txtDni.getText();
        ClsEEmpleado objEE=new ClsEEmpleado();
        ClsNEmpleado objNE=new ClsNEmpleado();
        objEE.setDniEmpleado(dni);
        if(objNE.MtdBuscarEmpleado(objEE)==true)
        {
            
        }
        else
        {
            JOptionPane.showMessageDialog(null, "ERROR");
        }
    }
}
