/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentación;

import Entidad.ClsEProveedor;
import Negocio.ClsNProveedor;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Usuario
 */
public class FrmProveedor extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmProveedor
     */
    public FrmProveedor() {
        initComponents();
        try {
            this.setMaximum(true);
        
        } catch (Exception e) {
        }
        rbtnActivo.setSelected(true);
        rbtnIdProveedor.setSelected(true);
        MtdListarProveedor();
    }
    DefaultTableModel modelo;
    TableRowSorter trs;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        rbtnIdProveedor = new javax.swing.JRadioButton();
        rbtnNombre = new javax.swing.JRadioButton();
        rbtnRuc = new javax.swing.JRadioButton();
        rbtnDni = new javax.swing.JRadioButton();
        txtBuscar = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProveedor = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblIdProveedor = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        txtIdProveedor = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblRuc = new javax.swing.JLabel();
        txtRuc = new javax.swing.JTextField();
        lblDni = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        lblCelular = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblNCuenta = new javax.swing.JLabel();
        txtNCuenta = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        rbtnActivo = new javax.swing.JRadioButton();
        rbtnInactivo = new javax.swing.JRadioButton();
        btnGuardar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rbtnIdProveedor.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup2.add(rbtnIdProveedor);
        rbtnIdProveedor.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        rbtnIdProveedor.setText("ID Proveedor");
        jPanel1.add(rbtnIdProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        rbtnNombre.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup2.add(rbtnNombre);
        rbtnNombre.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        rbtnNombre.setText("Nombre o razón social");
        jPanel1.add(rbtnNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        rbtnRuc.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup2.add(rbtnRuc);
        rbtnRuc.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        rbtnRuc.setText("RUC");
        jPanel1.add(rbtnRuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, -1, -1));

        rbtnDni.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup2.add(rbtnDni);
        rbtnDni.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        rbtnDni.setText("DNI");
        jPanel1.add(rbtnDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, -1, -1));

        txtBuscar.setBackground(new java.awt.Color(153, 204, 255));
        txtBuscar.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 444, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 690, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 690, 10));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 690, 10));

        tbProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbProveedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbProveedor);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 690, 320));
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 780, 590));

        jTabbedPane1.addTab("Buscar", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIdProveedor.setBackground(new java.awt.Color(0, 51, 51));
        lblIdProveedor.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblIdProveedor.setText("ID Proveedor");
        jPanel2.add(lblIdProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, 30));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 720, 10));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 710, 10));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 710, 10));
        jPanel2.add(txtIdProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 73, 30));

        lblNombre.setBackground(new java.awt.Color(0, 51, 51));
        lblNombre.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblNombre.setText("Nombre o razón social");
        jPanel2.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, 30));
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 190, 30));

        lblRuc.setBackground(new java.awt.Color(0, 51, 51));
        lblRuc.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblRuc.setText("RUC");
        jPanel2.add(lblRuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, 30));
        jPanel2.add(txtRuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 191, 30));

        lblDni.setBackground(new java.awt.Color(0, 51, 51));
        lblDni.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblDni.setText("DNI");
        jPanel2.add(lblDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, 30));
        jPanel2.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 119, 30));

        lblDireccion.setBackground(new java.awt.Color(0, 51, 51));
        lblDireccion.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblDireccion.setText("Direccion");
        jPanel2.add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, -1, 30));
        jPanel2.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 230, 30));

        lblCelular.setBackground(new java.awt.Color(0, 51, 51));
        lblCelular.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblCelular.setText("Celular");
        jPanel2.add(lblCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, 30));
        jPanel2.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 170, 30));

        lblEmail.setBackground(new java.awt.Color(0, 51, 51));
        lblEmail.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblEmail.setText("Email");
        jPanel2.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, -1, 30));
        jPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 234, 30));

        lblNCuenta.setBackground(new java.awt.Color(0, 51, 51));
        lblNCuenta.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblNCuenta.setText("Nro Cuenta");
        jPanel2.add(lblNCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, -1, 30));
        jPanel2.add(txtNCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 170, 30));

        lblEstado.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblEstado.setForeground(new java.awt.Color(255, 255, 255));
        lblEstado.setText("Estado");
        jPanel2.add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, -1, 30));

        rbtnActivo.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(rbtnActivo);
        rbtnActivo.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        rbtnActivo.setText("Activo");
        jPanel2.add(rbtnActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, -1, -1));

        rbtnInactivo.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(rbtnInactivo);
        rbtnInactivo.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        rbtnInactivo.setText("Inactivo");
        jPanel2.add(rbtnInactivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, -1, -1));

        btnGuardar.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnGuardar.setText(" GUARDAR");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 210, 50));

        btnNuevo.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnNuevo.setText("NUEVO");
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevo.setVerifyInputWhenFocusTarget(false);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel2.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 210, 50));

        btnModificar.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnModificar.setText("MODIFICAR");
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel2.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, 210, 50));

        jLabel11.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 590));

        jTabbedPane1.addTab("Nuevo / Modificar", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        MtdLimpiarCaja();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        ClsEProveedor objEE=new ClsEProveedor();
        ClsNProveedor objNE=new ClsNProveedor();
        objEE.setDni(txtDni.getText());
        objEE.setNombre(txtNombre.getText());
        objEE.setRuc(txtRuc.getText());
        objEE.setDireccion(txtDireccion.getText());
        objEE.setCelular(txtCelular.getText());
        objEE.setEmail(txtEmail.getText());
        objEE.setNCuenta(txtNCuenta.getText());
     
        if(rbtnActivo.isSelected())
        {
            objEE.setEstado(1);
        }
        else
        {
            objEE.setEstado(0);
        }
            
        if(objNE.MtdResgistrarProveedor(objEE)==true)
        {
            JOptionPane.showMessageDialog(null, "PROVEEDOR AGREGADO");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "NO SE PUDO GUARDAR DATOS");
        }
        MtdListarProveedor();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        ClsEProveedor objEE=new ClsEProveedor();
        ClsNProveedor objNE=new ClsNProveedor();
        objEE.setIdProveedor(Integer.parseInt(txtIdProveedor.getText()));
        objEE.setDni(txtDni.getText());
        objEE.setNombre(txtNombre.getText());
        objEE.setRuc(txtRuc.getText());
        objEE.setDireccion(txtDireccion.getText());
        objEE.setCelular(txtCelular.getText());
        objEE.setEmail(txtEmail.getText());
        objEE.setNCuenta(txtNCuenta.getText());
     
        if(rbtnActivo.isSelected())
        {
            objEE.setEstado(1);
        }
        else
        {
            objEE.setEstado(0);
        }
            
        if(objNE.MtdModificarProveedor(objEE)==true)
        {
            JOptionPane.showMessageDialog(null, "PROVEEDOR MODIFICADO");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "NO SE PUDO GUARDAR DATOS");
        }
        MtdListarProveedor();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
        txtBuscar.addKeyListener(new KeyAdapter()
        {
            public void keyRelease(KeyEvent e){
                if(rbtnIdProveedor.isSelected()){
                    trs.setRowFilter(RowFilter.regexFilter("(?i)"+ txtBuscar.getText(),0));
                }
                if (rbtnNombre.isSelected()){
                    trs.setRowFilter(RowFilter.regexFilter("(?i)"+txtBuscar.getText(),1));
                }
                if (rbtnDni.isSelected()){
                    trs.setRowFilter(RowFilter.regexFilter("(?i)"+txtBuscar.getText(),2));
                }
                if (rbtnRuc.isSelected()){
                    trs.setRowFilter(RowFilter.regexFilter("(?i)"+txtBuscar.getText(),3));
                }                     
            }
        }
        );
        trs=new TableRowSorter(modelo);
        tbProveedor.setRowSorter(trs);
    }//GEN-LAST:event_txtBuscarKeyTyped

    private void tbProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProveedorMouseClicked
       int filam;                                   //PASAR DATOS DE LA TABLA A LAS CAJAS DE TEXTO
        filam=tbProveedor.getSelectedRow();   
        txtIdProveedor.setText(tbProveedor.getValueAt(filam, 0).toString());
        txtDni.setText(tbProveedor.getValueAt(filam, 1).toString());
        txtNombre.setText(tbProveedor.getValueAt(filam, 2).toString());
        txtRuc.setText(tbProveedor.getValueAt(filam, 3).toString());
        txtDireccion.setText(tbProveedor.getValueAt(filam, 4).toString());
        txtCelular.setText(tbProveedor.getValueAt(filam, 5).toString());
        txtEmail.setText(tbProveedor.getValueAt(filam, 6).toString());
        txtNCuenta.setText(tbProveedor.getValueAt(filam, 7).toString());
        if(tbProveedor.getValueAt(filam, 8).toString().equals("ACTIVO"))
        {
            rbtnActivo.setSelected(true);
        }
        else
        {
            rbtnInactivo.setSelected(true);
        }
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_tbProveedorMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblIdProveedor;
    private javax.swing.JLabel lblNCuenta;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRuc;
    private javax.swing.JRadioButton rbtnActivo;
    private javax.swing.JRadioButton rbtnDni;
    private javax.swing.JRadioButton rbtnIdProveedor;
    private javax.swing.JRadioButton rbtnInactivo;
    private javax.swing.JRadioButton rbtnNombre;
    private javax.swing.JRadioButton rbtnRuc;
    private javax.swing.JTable tbProveedor;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIdProveedor;
    private javax.swing.JTextField txtNCuenta;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRuc;
    // End of variables declaration//GEN-END:variables

    private void MtdListarProveedor() {
        modelo=new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("DNI");
        modelo.addColumn("NOMBRE/RAZON");
        modelo.addColumn("RUC");
        modelo.addColumn("DIRECCION");
        modelo.addColumn("CELULAR");
        modelo.addColumn("EMAIL");
        modelo.addColumn("NRO CUENTA");
        modelo.addColumn("ESTADO");
        ClsNProveedor objNE=new ClsNProveedor();
        String[] datos=new String[9];
        for(ClsEProveedor objE : objNE.MtdListarProveedor())
        {
            datos[0]=String.valueOf(objE.getIdProveedor());
            datos[1]=objE.getDni();
            datos[2]=objE.getNombre();
            datos[3]=objE.getRuc();
            datos[4]=objE.getDireccion();
            datos[5]=objE.getCelular();
            datos[6]=objE.getEmail();
            datos[7]=objE.getNCuenta();
            if(objE.getEstado()==0)
            {
                datos[8]="INACTIVO";
            }
            else
            {
                datos[8]="ACTIVO";  
            }
            modelo.addRow(datos);
        }
        this.tbProveedor.setModel(modelo);
    }

    private void MtdLimpiarCaja() {
        txtIdProveedor.setText("");
        txtCelular.setText("");
        txtDireccion.setText("");
        txtDni.setText("");
        txtEmail.setText("");
        txtNCuenta.setText("");
        txtNombre.setText("");
        txtRuc.setText("");
    }
}
