/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentación;

import Entidad.ClsEProducto;
import Entidad.ClsEUnidad;
import Negocio.ClsNProducto;
import Negocio.ClsNUnidad;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Usuario
 */
public class FrmProducto extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmProducto
     */
    public FrmProducto() {
        initComponents();
        try {
            this.setMaximum(true);
        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
        rbtnActivo.setSelected(true);
        rbtnCodigobarras.setSelected(true);
        MtdListarProducto();
        
        MtdLimpiar();
    }
    DefaultTableModel modelo;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        rbtnCodigobarras = new javax.swing.JRadioButton();
        rbtnNombre = new javax.swing.JRadioButton();
        rbtnUnidad = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProducto1 = new javax.swing.JTable();
        txtBuscar2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblIdProducto = new javax.swing.JLabel();
        txtIdProducto = new javax.swing.JTextField();
        lblCodigoBarras = new javax.swing.JLabel();
        txtCodigoBarras = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        txtNombre = new javax.swing.JTextField();
        lblUnidad = new javax.swing.JLabel();
        cmbUnidad = new javax.swing.JComboBox<>();
        lblEstado = new javax.swing.JLabel();
        rbtnActivo = new javax.swing.JRadioButton();
        rbtnInactivo = new javax.swing.JRadioButton();
        lblStockMinimo = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        lblPrecioVenta = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        txtUnidadesCaja = new javax.swing.JTextField();
        fondoformulario = new javax.swing.JLabel();
        lblPrecioVenta1 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rbtnCodigobarras.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup2.add(rbtnCodigobarras);
        rbtnCodigobarras.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        rbtnCodigobarras.setText("Código de barras");
        jPanel1.add(rbtnCodigobarras, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        rbtnNombre.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup2.add(rbtnNombre);
        rbtnNombre.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        rbtnNombre.setText("Nombre");
        jPanel1.add(rbtnNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));

        rbtnUnidad.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup2.add(rbtnUnidad);
        rbtnUnidad.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        rbtnUnidad.setText("Unidad");
        jPanel1.add(rbtnUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 680, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 680, 10));

        tbProducto1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbProducto1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbProducto1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbProducto1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 680, 217));

        txtBuscar2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscar2KeyTyped(evt);
            }
        });
        jPanel1.add(txtBuscar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 370, 30));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 590));

        jTabbedPane1.addTab("Buscar", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIdProducto.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblIdProducto.setText("ID producto");
        jPanel2.add(lblIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, 30));
        jPanel2.add(txtIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 50, 30));

        lblCodigoBarras.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblCodigoBarras.setText("Código de barras");
        jPanel2.add(lblCodigoBarras, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, 30));
        jPanel2.add(txtCodigoBarras, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 170, 30));

        lblNombre.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblNombre.setText("Nombre");
        jPanel2.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, 30));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 700, 10));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 700, 10));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, 700, 10));
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 180, 30));

        lblUnidad.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblUnidad.setText("Unidad");
        jPanel2.add(lblUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, 30));

        cmbUnidad.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        cmbUnidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cmbUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 113, 30));

        lblEstado.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblEstado.setText("Estado");
        jPanel2.add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 60, 30));

        buttonGroup1.add(rbtnActivo);
        rbtnActivo.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        rbtnActivo.setText("Activo");
        jPanel2.add(rbtnActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, -1, -1));

        buttonGroup1.add(rbtnInactivo);
        rbtnInactivo.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        rbtnInactivo.setText("Inactivo");
        jPanel2.add(rbtnInactivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, -1, -1));

        lblStockMinimo.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblStockMinimo.setText("Stock");
        jPanel2.add(lblStockMinimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, -1, 30));
        jPanel2.add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 85, 30));

        lblPrecioVenta.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblPrecioVenta.setText("Unidades por caja");
        jPanel2.add(lblPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, 30));

        btnNuevo.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnNuevo.setText("NUEVO");
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel2.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 210, 50));

        btnGuardar.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnGuardar.setText(" GUARDAR");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 500, 210, 50));

        btnModificar.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnModificar.setText(" MODIFICAR");
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel2.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 500, 210, 50));
        jPanel2.add(txtUnidadesCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 85, 30));
        jPanel2.add(fondoformulario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 590));

        lblPrecioVenta1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblPrecioVenta1.setForeground(new java.awt.Color(255, 255, 255));
        lblPrecioVenta1.setText("Precio de venta");
        jPanel2.add(lblPrecioVenta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, -1, 30));

        jTabbedPane1.addTab("Nuevo / Modificar", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        ClsEProducto objEE=new ClsEProducto();
        ClsNProducto objNE=new ClsNProducto();
        objEE.setNombre(txtNombre.getText());
        objEE.setCBarras(txtCodigoBarras.getText());
        objEE.setIdUnidad(cmbUnidad.getSelectedIndex()+1);
        objEE.setuCajas(Integer.parseInt(txtUnidadesCaja.getText()));
        objEE.setStock(Integer.parseInt(txtStock.getText()));

        if(rbtnActivo.isSelected())
        {
            objEE.setEstado(1);
        }
        else
        {
            objEE.setEstado(0);
        }
            
        if(objNE.MtdResgistrarProducto(objEE)==true)
        {
            JOptionPane.showMessageDialog(null, "PRODUCTO AGREGADO");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "NO SE PUDO GUARDAR DATOS");
        }
        MtdListarProducto();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
       cmbUnidad.removeAllItems();
        LlenarCombo();
       MtdLimpiar();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        ClsEProducto objEE=new ClsEProducto();
        ClsNProducto objNE=new ClsNProducto();
        objEE.setCBarras(txtCodigoBarras.getText());
        objEE.setNombre(txtNombre.getText());
        objEE.setStock(Integer.parseInt(txtStock.getText()));
        objEE.setIdUnidad(cmbUnidad.getSelectedIndex()+1);
        objEE.setuCajas(Integer.parseInt(txtUnidadesCaja.getText()));
        if(rbtnActivo.isSelected())
        {
            objEE.setEstado(1);
        }
        else
        {
            objEE.setEstado(0);
        }
        if(objNE.MtdModificarProducto(objEE)==true)
        {
            JOptionPane.showMessageDialog(null, "DATOS MODIFICADOS CORRECTAMENTE");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "NO SE PUDO MODIFICAR EL DATO");
        }
        MtdListarProducto();
        MtdLimpiar();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void tbProducto1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProducto1MouseClicked
        int filam;                                   //PASAR DATOS DE LA TABLA A LAS CAJAS DE TEXTO
        filam=tbProducto1.getSelectedRow();   
        txtCodigoBarras.setText(tbProducto1.getValueAt(filam, 0).toString());
        txtNombre.setText(tbProducto1.getValueAt(filam, 1).toString());
        txtUnidadesCaja.setText(tbProducto1.getValueAt(filam, 2).toString());
        cmbUnidad.setSelectedIndex(Integer.parseInt(tbProducto1.getValueAt(filam, 3).toString())-1);
        
        txtStock.setText(tbProducto1.getValueAt(filam, 6).toString());
        if(tbProducto1.getValueAt(filam, 7).toString().equals("ACTIVO"))
        {
            rbtnActivo.setSelected(true);
        }
        else
        {
            rbtnInactivo.setSelected(true);
        }
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_tbProducto1MouseClicked
TableRowSorter trs;
    private void txtBuscar2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscar2KeyTyped
              
        txtBuscar2.addKeyListener(new KeyAdapter()
        {
            public void keyRelease(KeyEvent e){
                if(rbtnCodigobarras.isSelected()){
                    trs.setRowFilter(RowFilter.regexFilter("(?i)"+ txtBuscar2.getText(),0));
                }
                if (rbtnNombre.isSelected()){
                    trs.setRowFilter(RowFilter.regexFilter("(?i)"+txtBuscar2.getText(),1));
                }
                if (rbtnUnidad.isSelected()){
                    trs.setRowFilter(RowFilter.regexFilter("(?i)"+txtBuscar2.getText(),2));
                }
                        
            }
        }
        );
        trs=new TableRowSorter(modelo);
        tbProducto1.setRowSorter(trs);
    }//GEN-LAST:event_txtBuscar2KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cmbUnidad;
    private javax.swing.JLabel fondoformulario;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCodigoBarras;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblIdProducto;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecioVenta;
    private javax.swing.JLabel lblPrecioVenta1;
    private javax.swing.JLabel lblStockMinimo;
    private javax.swing.JLabel lblUnidad;
    private javax.swing.JRadioButton rbtnActivo;
    private javax.swing.JRadioButton rbtnCodigobarras;
    private javax.swing.JRadioButton rbtnInactivo;
    private javax.swing.JRadioButton rbtnNombre;
    private javax.swing.JRadioButton rbtnUnidad;
    private javax.swing.JTable tbProducto1;
    private javax.swing.JTextField txtBuscar2;
    private javax.swing.JTextField txtCodigoBarras;
    private javax.swing.JTextField txtIdProducto;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtUnidadesCaja;
    // End of variables declaration//GEN-END:variables

    public void MtdListarProducto() {
        modelo=new DefaultTableModel();
        modelo.addColumn("CODIGO BARRAS");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("UNIDADES CAJAS");
        modelo.addColumn("UNIDAD");
        modelo.addColumn("STOCK MINIMO");
        modelo.addColumn("STOCK MAXIMO");
        modelo.addColumn("STOCK");
        modelo.addColumn("ESTADO");
        ClsNProducto objNE=new ClsNProducto();
        String[] datos=new String[8];
        for(ClsEProducto objE : objNE.MtdListarProducto())
        {
            datos[0]=objE.getCBarras();
            datos[1]=objE.getNombre();
            datos[2]=String.valueOf(objE.getuCajas());
            datos[3]=String.valueOf(objE.getIdUnidad());
            datos[4]=String.valueOf(objE.getsMinimo());
            datos[5]=String.valueOf(objE.getsMaximo());
            datos[6]=String.valueOf(objE.getStock());
            if(objE.getEstado()==0)
            {
                datos[7]="INACTIVO";
            }
            else
            {
                datos[7]="ACTIVO";  
            }
            modelo.addRow(datos);
        }
        this.tbProducto1.setModel(modelo);
    }

    private void MtdLimpiar() {
        txtIdProducto.setText("");
         txtNombre.setText("");
         txtCodigoBarras.setText("");
         txtStock.setText("");
         txtUnidadesCaja.setText("");
         cmbUnidad.setSelectedIndex(0);
    }

    public void LlenarCombo() {
        String []prueba=new String[1];
        DefaultComboBoxModel value = new DefaultComboBoxModel();
        cmbUnidad.removeAllItems();
        cmbUnidad.setModel(value);    
            ClsNUnidad objN =new ClsNUnidad();
        for(ClsEUnidad objE : objN.LlenarUnidad())
        {
            prueba[0]=objE.getDescripcionUnidad();
            value.addElement(prueba[0]);         
        }    
    }
}
