/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentación;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Usuario
 */
public class FrmReportes extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmReportes
     */
    public FrmReportes() {
        initComponents();
        try {
            this.setMaximum(true);
        
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReporte1 = new javax.swing.JButton();
        btnGrafico = new javax.swing.JButton();
        btninactivos = new javax.swing.JButton();

        btnReporte1.setText("Ingresos y salidas de empleados");
        btnReporte1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporte1ActionPerformed(evt);
            }
        });

        btnGrafico.setText("Gráfico para trabajadores");
        btnGrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficoActionPerformed(evt);
            }
        });

        btninactivos.setText("Productos inactivos");
        btninactivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninactivosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnReporte1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                    .addComponent(btnGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btninactivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btnReporte1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btninactivos, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReporte1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporte1ActionPerformed
         JasperReport repo;
        Connection con;
        try {
              Class.forName("com.mysql.jdbc.Driver");
//              con =DriverManager.getConnection("jdbc:mysql://localhost:3306/db_ejemplo","root","");
              con=DriverManager.getConnection("jdbc:mysql://localhost:3307/bd_boticainv","root","");
              repo=JasperCompileManager.compileReport("src/Reportes/IngresosYSalidas.jrxml");
              JasperPrint jp=JasperFillManager.fillReport(repo,null,con);
              JasperViewer.viewReport(jp,true);
                //ClassNotFoundException
        }
        catch (ClassNotFoundException| SQLException |JRException  ex) {
                JOptionPane.showMessageDialog(null,"ocurrio este error"+ ex);
        }
    }//GEN-LAST:event_btnReporte1ActionPerformed

    private void btnGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficoActionPerformed
          JasperReport repo;
        Connection con;
        try {
              Class.forName("com.mysql.jdbc.Driver");
//              con =DriverManager.getConnection("jdbc:mysql://localhost:3306/db_ejemplo","root","");
              con=DriverManager.getConnection("jdbc:mysql://localhost:3307/bd_boticainv","root","");
              repo=JasperCompileManager.compileReport("src/Reportes/Empleados.jrxml");
              JasperPrint jp=JasperFillManager.fillReport(repo,null,con);
              JasperViewer.viewReport(jp,true);
                //ClassNotFoundException
        }
        catch (ClassNotFoundException| SQLException |JRException  ex) {
                JOptionPane.showMessageDialog(null,"ocurrio este error"+ ex);
        }
    }//GEN-LAST:event_btnGraficoActionPerformed

    private void btninactivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninactivosActionPerformed
        JasperReport repo;
        Connection con;
        try {
              Class.forName("com.mysql.jdbc.Driver");
//              con =DriverManager.getConnection("jdbc:mysql://localhost:3306/db_ejemplo","root","");
              con=DriverManager.getConnection("jdbc:mysql://localhost:3307/bd_boticainv","root","");
              repo=JasperCompileManager.compileReport("src/Reportes/ProductosInactivos.jrxml");
              JasperPrint jp=JasperFillManager.fillReport(repo,null,con);
              JasperViewer.viewReport(jp,true);
                //ClassNotFoundException
        }
        catch (ClassNotFoundException| SQLException |JRException  ex) {
                JOptionPane.showMessageDialog(null,"ocurrio este error"+ ex);
        }
    }//GEN-LAST:event_btninactivosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGrafico;
    private javax.swing.JButton btnReporte1;
    private javax.swing.JButton btninactivos;
    // End of variables declaration//GEN-END:variables
}
