/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentación;
import Entidad.ClsEUnidad;
import Negocio.ClsNUnidad;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author Usuario
 */
public class FrmUnidad extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmUnidad
     */
    public FrmUnidad() {
        initComponents();
        try {
            this.setMaximum(true);
        
        } catch (Exception e) {
        }
        rbtnIdUnidad.setSelected(true);
        MtdListarUnidad();
    }
    DefaultTableModel modelo;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        rbtnIdUnidad = new javax.swing.JRadioButton();
        rbtnDescripcion = new javax.swing.JRadioButton();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbUnidad = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblIdUnidad = new javax.swing.JLabel();
        txtIdUnidad = new javax.swing.JTextField();
        lblDescripcion = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 670, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 670, 10));

        rbtnIdUnidad.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(rbtnIdUnidad);
        rbtnIdUnidad.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        rbtnIdUnidad.setText("ID Unidad");
        jPanel1.add(rbtnIdUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        rbtnDescripcion.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(rbtnDescripcion);
        rbtnDescripcion.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        rbtnDescripcion.setText("Descripcion");
        jPanel1.add(rbtnDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        txtBuscar.setBackground(new java.awt.Color(153, 204, 255));
        txtBuscar.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 248, 30));

        tbUnidad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbUnidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbUnidadMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbUnidad);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 670, 163));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 590));

        jTabbedPane1.addTab("Buscar", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIdUnidad.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblIdUnidad.setText("ID Unidad");
        jPanel2.add(lblIdUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, 30));

        txtIdUnidad.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jPanel2.add(txtIdUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 70, 30));

        lblDescripcion.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblDescripcion.setText("Descripción");
        jPanel2.add(lblDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, -1, 30));

        txtDescripcion.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jPanel2.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 140, 30));

        jButton1.setText("GUARDAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 110, 50));

        jButton2.setText("MODIFICAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 110, 50));

        btnNuevo.setText("NUEVO");
        jPanel2.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 100, 50));

        jTabbedPane1.addTab("Nuevo / Modificar", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbUnidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbUnidadMouseClicked
        int filam;                                   //PASAR DATOS DE LA TABLA A LAS CAJAS DE TEXTO
        filam=tbUnidad.getSelectedRow();
        txtIdUnidad.setText(tbUnidad.getValueAt(filam, 0).toString());
        txtDescripcion.setText(tbUnidad.getValueAt(filam, 1).toString());
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_tbUnidadMouseClicked

    TableRowSorter trs;
    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
        txtBuscar.addKeyListener(new KeyAdapter()
        {
            public void keyReleased(KeyEvent e){
                
                if (rbtnIdUnidad.isSelected()){
                    trs.setRowFilter(RowFilter.regexFilter("(?i)"+txtBuscar.getText(),0));
                }
                if (rbtnDescripcion.isSelected()){
                    trs.setRowFilter(RowFilter.regexFilter("(?i)"+txtBuscar.getText(),1));
                }
            }
        }
        );
        trs=new TableRowSorter(modelo);
        tbUnidad.setRowSorter(trs);
    }//GEN-LAST:event_txtBuscarKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ClsEUnidad objEC=new ClsEUnidad();
        ClsNUnidad objNC=new ClsNUnidad();
        objEC.setDescripcionUnidad(txtDescripcion.getText());

        if(objNC.MtdResgistrarUnidad(objEC)==true)
        {
            JOptionPane.showMessageDialog(null, "UNIDAD REGISTRADA");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "NO SE PUDO GUARDAR EL DATO");
        }
        MtdListarUnidad();
        MtdLimpiar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ClsEUnidad objEC=new ClsEUnidad();
        ClsNUnidad objNC=new ClsNUnidad();
        objEC.setIdUnidad(Integer.parseInt(txtIdUnidad.getText()));
        objEC.setDescripcionUnidad(txtDescripcion.getText());
        if(objNC.MtdModificarUnidad(objEC)==true)
        {
            JOptionPane.showMessageDialog(null, "DATOS MODIFICADOS CORRECTAMENTE");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "NO SE PUDO MODIFICAR EL DATO");
        }
        MtdListarUnidad();
        MtdLimpiar();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblIdUnidad;
    private javax.swing.JRadioButton rbtnDescripcion;
    private javax.swing.JRadioButton rbtnIdUnidad;
    private javax.swing.JTable tbUnidad;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtIdUnidad;
    // End of variables declaration//GEN-END:variables

    private void MtdListarUnidad() {
         modelo=new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("DESCRIPCION");
        ClsNUnidad objNC=new ClsNUnidad();
        String[] datos=new String[2];
        for(ClsEUnidad objE : objNC.MtdListarUnidad())
        {          
            datos[0]=String.valueOf(objE.getIdUnidad());
            datos[1]=String.valueOf(objE.getDescripcionUnidad());
            modelo.addRow(datos);
        }
        this.tbUnidad.setModel(modelo);
    }

    private void MtdLimpiar() {
        txtIdUnidad.setText("");
        txtDescripcion.setText("");
    }
}
