/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentación;

import Entidad.ClsEEmpleado;
import Negocio.ClsNEmpleado;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */

public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    FrmProducto pnlProducto=new FrmProducto();
    FrmEmpleado pnlEmpleado=new FrmEmpleado();
    FrmKardex pnlKardex=new FrmKardex();
    FrmUnidad pnlUnidad=new FrmUnidad();
    FrmProveedor pnlProveedor=new FrmProveedor();
    FrmImprimir pnlImprimir=new FrmImprimir();
    FrmReportes pnlReportes=new FrmReportes();
    FrmModificar pnlModificar=new FrmModificar();
    
    public static int codigoproducto;
    public static int IDempleado;
    public static String dni1;
    public static int ayuda=0;
    public Principal(String dni,String Tipo, String Nombre,String IdEmpleado) {
        initComponents();
        this.setExtendedState(NORMAL);
        this.setLocationRelativeTo(this);
        setLocationRelativeTo(null);
        txtNombre.setText(Nombre);
        txtDni.setText(dni);
        IDempleado=Integer.parseInt(IdEmpleado);
        dni1=dni;
        if(Tipo.equals("ADMINISTRADOR"))
        {
            
        }
        else
        {
            btnUsuario.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlVentanas = new javax.swing.JDesktopPane();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        btnUsuario = new javax.swing.JButton();
        btnKardex = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        btnProducto = new javax.swing.JButton();
        btnUnidad = new javax.swing.JButton();
        btnProveedor = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnConf = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlVentanas.setPreferredSize(new java.awt.Dimension(1324, 807));

        javax.swing.GroupLayout pnlVentanasLayout = new javax.swing.GroupLayout(pnlVentanas);
        pnlVentanas.setLayout(pnlVentanasLayout);
        pnlVentanasLayout.setHorizontalGroup(
            pnlVentanasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1227, Short.MAX_VALUE)
        );
        pnlVentanasLayout.setVerticalGroup(
            pnlVentanasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Bienvenido(a):");

        txtNombre.setEditable(false);
        txtNombre.setColumns(20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Dni:");

        txtDni.setEditable(false);

        btnUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUsuario.setText("USUARIO");
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });

        btnKardex.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnKardex.setText("KARDEX");
        btnKardex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKardexActionPerformed(evt);
            }
        });

        btnCerrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCerrar.setText("CERRAR SESION");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnProducto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnProducto.setText("PRODUCTO");
        btnProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoActionPerformed(evt);
            }
        });

        btnUnidad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUnidad.setText("UNIDAD");
        btnUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnidadActionPerformed(evt);
            }
        });

        btnProveedor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnProveedor.setText("PROVEEDOR");
        btnProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedorActionPerformed(evt);
            }
        });

        btnImprimir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnImprimir.setText("IMPRIMIR KARDEX");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        btnReportes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnReportes.setText("REPORTES");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        btnConf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnConf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/configure.png"))); // NOI18N
        btnConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlVentanas, javax.swing.GroupLayout.PREFERRED_SIZE, 1227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnUsuario)
                        .addGap(28, 28, 28)
                        .addComponent(btnUnidad)
                        .addGap(18, 18, 18)
                        .addComponent(btnProducto)
                        .addGap(18, 18, 18)
                        .addComponent(btnProveedor)
                        .addGap(18, 18, 18)
                        .addComponent(btnKardex)
                        .addGap(18, 18, 18)
                        .addComponent(btnImprimir)
                        .addGap(18, 18, 18)
                        .addComponent(btnReportes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCerrar)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnKardex, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlVentanas, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnConf, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 546, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed

        pnlVentanas.add(pnlEmpleado);
        pnlEmpleado.show();
        pnlUnidad.dispose();
        pnlKardex.dispose();
        pnlProveedor.dispose();
        pnlProducto.dispose();
        pnlImprimir.dispose();
        pnlReportes.dispose();
        pnlModificar.dispose();
        pnlEmpleado.LlenarCombo();
        pnlEmpleado.MtdListarEmpleado();
    }//GEN-LAST:event_btnUsuarioActionPerformed

    private void btnKardexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKardexActionPerformed
        pnlVentanas.add(pnlKardex);
        pnlKardex.show();
        pnlEmpleado.dispose();
        pnlUnidad.dispose();
        pnlProveedor.dispose();
        pnlProducto.dispose();
        pnlImprimir.dispose();
        pnlReportes.dispose();
        pnlModificar.dispose();
        pnlKardex.MtdlistarProductos();
        pnlKardex.LlenarProveedor();
        pnlKardex.LlenarDocumento();
        pnlKardex.MtdListar();
    }//GEN-LAST:event_btnKardexActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
    
        Date date=new Date();
        ClsNEmpleado objNE=new ClsNEmpleado();
        ClsEEmpleado objEE=new ClsEEmpleado();
            SimpleDateFormat dateFormatLocal=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            objEE.setFechaSalida(String.valueOf(dateFormatLocal.format(date)));
            objEE.setDniEmpleado(dni1);
            if(objNE.MtdResgistroHoraSalida(objEE)==true)
            {
                FrmLogin log=new FrmLogin();
                log.show();
                this.dispose();
            }
        

    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoActionPerformed
        pnlVentanas.add(pnlProducto);
        pnlProducto.show();
        pnlEmpleado.dispose();
        pnlImprimir.dispose();
        pnlKardex.dispose();
        pnlProveedor.dispose();
        pnlUnidad.dispose();
        pnlReportes.dispose();
        pnlModificar.dispose();
        pnlProducto.LlenarCombo();
        pnlProducto.MtdListarProducto();
    }//GEN-LAST:event_btnProductoActionPerformed

    private void btnUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnidadActionPerformed
        pnlVentanas.add(pnlUnidad);
        pnlUnidad.show();
        pnlEmpleado.dispose();
        pnlImprimir.dispose();
        pnlKardex.dispose();
        pnlReportes.dispose();
        pnlProveedor.dispose();
        pnlProducto.dispose();
        pnlModificar.dispose();
    }//GEN-LAST:event_btnUnidadActionPerformed

    private void btnProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedorActionPerformed
        pnlVentanas.add(pnlProveedor);
        pnlProveedor.show();
        pnlEmpleado.dispose();
        pnlUnidad.dispose();
        pnlImprimir.dispose();
        pnlReportes.dispose();
        pnlKardex.dispose();
        pnlModificar.dispose();
        pnlProducto.dispose();
    }//GEN-LAST:event_btnProveedorActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        pnlVentanas.add(pnlImprimir);
        pnlImprimir.show();
        pnlEmpleado.dispose();
        pnlUnidad.dispose();
        pnlProveedor.dispose();
        pnlReportes.dispose();
        pnlKardex.dispose();
        pnlProducto.dispose();
        pnlModificar.dispose();
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        pnlVentanas.add(pnlReportes);
        pnlReportes.show();
        pnlEmpleado.dispose();
        pnlUnidad.dispose();
        pnlProveedor.dispose();
        pnlImprimir.dispose();
        pnlKardex.dispose();
        pnlProducto.dispose();
        pnlModificar.dispose();
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfActionPerformed
        pnlVentanas.add(pnlModificar);
        pnlModificar.show();
        pnlEmpleado.dispose();
        pnlUnidad.dispose();
        pnlProveedor.dispose();
        pnlImprimir.dispose();
        pnlKardex.dispose();
        pnlProducto.dispose();
        pnlReportes.dispose();
        pnlModificar.MtdListarDatos();
    }//GEN-LAST:event_btnConfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Principal().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnConf;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnKardex;
    private javax.swing.JButton btnProducto;
    private javax.swing.JButton btnProveedor;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnUnidad;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JDesktopPane pnlVentanas;
    public static javax.swing.JTextField txtDni;
    public static javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
